# Generated by Django 4.0.10 on 2023-07-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='name',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='Автор неизвестен', max_length=50, verbose_name='Автор книги'),
        ),
    ]
