# Generated by Django 4.0.10 on 2023-07-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_authors_alter_books_date_alter_books_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Artiles_authors',
        ),
    ]
